// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/pocblockchain/pocc/x/mint/internal/keeper
// ALIASGEN: github.com/pocblockchain/pocc/x/mint/internal/types
package mint

import (
	"github.com/pocblockchain/pocc/x/mint/internal/keeper"
	"github.com/pocblockchain/pocc/x/mint/internal/types"
)

const (
	ModuleName            = types.ModuleName
	DefaultParamspace     = types.DefaultParamspace
	StoreKey              = types.StoreKey
	QuerierRoute          = types.QuerierRoute
	QueryParameters       = types.QueryParameters
	QueryAnnualProvisions = types.QueryAnnualProvisions
)

var (
	// functions aliases
	NewKeeper            = keeper.NewKeeper
	NewQuerier           = keeper.NewQuerier
	NewMinter            = types.NewMinter
	InitialMinter        = types.InitialMinter
	DefaultInitialMinter = types.DefaultInitialMinter
	ValidateMinter       = types.ValidateMinter
	ParamKeyTable        = types.ParamKeyTable
	NewParams            = types.NewParams
	DefaultParams        = types.DefaultParams
	ValidateParams       = types.ValidateParams
	RegisterCodec        = types.RegisterCodec

	// variable aliases
	ModuleCdc                = types.ModuleCdc
	MinterKey                = types.MinterKey
	KeyMintDenom             = types.KeyMintDenom
	KeyInitalInflationAmount = types.KeyInitalInflationAmount
	KeyBlocksPerYear         = types.KeyBlocksPerYear
)

type (
	Keeper = keeper.Keeper
	Minter = types.Minter
	Params = types.Params
)
